import React,{useState}from"react";
import "./CasinoAdmin.css";
export default function CasinoAdmin(){
const[casino,setCasino]=useState({name:"Royal Win Casino",upi:"royalwin@upi",whatsapp:"+91 98765 43210",telegram:"@royalwinsupport",email:"support@royalwin.com"});
const[markets,setMarkets]=useState([{id:1,name:"Delhi Bazar",type:"Day",mode:"Manual",status:"Active"},{id:2,name:"Kalyan",type:"Day",mode:"Manual",status:"Active"},{id:3,name:"Mumbai Main",type:"Day",mode:"Manual",status:"Active"},{id:4,name:"Rajdhani Day",type:"Day",mode:"Auto",status:"Active"},{id:5,name:"Time Bazar",type:"Night",mode:"Manual",status:"Active"},{id:6,name:"Milan Day",type:"Day",mode:"Auto",status:"Inactive"},{id:7,name:"Madhur Day",type:"Day",mode:"Manual",status:"Active"},{id:8,name:"Sridevi Night",type:"Night",mode:"Auto",status:"Active"},{id:9,name:"Delhi Main",type:"Night",mode:"Manual",status:"Active"},{id:10,name:"Pune Market",type:"Day",mode:"Manual",status:"Active"}]);
const[timings,setTimings]=useState([{id:1,market:"Delhi Bazar",open:"10:00",close:"11:00",result:"11:15",betClose:"5",days:"Mon - Sat"},{id:2,market:"Kalyan",open:"11:30",close:"12:30",result:"12:45",betClose:"5",days:"Mon - Sat"},{id:3,market:"Mumbai Main",open:"13:00",close:"14:00",result:"14:15",betClose:"5",days:"Mon - Sat"}]);
const[starLines,setStarLines]=useState([{id:1,name:"Star Line Morning",type:"Day",open:"09:00",close:"09:30",result:"09:45",status:"Active"},{id:2,name:"Star Line Night",type:"Night",open:"21:00",close:"21:30",result:"21:45",status:"Active"}]);
const[marketForm,setMarketForm]=useState({name:"",type:"Day",mode:"Manual",status:"Active"});
const[timingForm,setTimingForm]=useState({market:"",open:"",close:"",result:"",betClose:"5",days:"Mon - Sat"});
const[starForm,setStarForm]=useState({name:"",type:"Day",open:"",close:"",result:"",status:"Active"});
const change=e=>setCasino({...casino,[e.target.name]:e.target.value});
const changeMarket=e=>setMarketForm({...marketForm,[e.target.name]:e.target.value});
const changeTiming=e=>setTimingForm({...timingForm,[e.target.name]:e.target.value});
const changeStar=e=>setStarForm({...starForm,[e.target.name]:e.target.value});
const addMarket=()=>{if(!marketForm.name.trim())return alert("Market name required");setMarkets([...markets,{id:Date.now(),...marketForm,name:marketForm.name.trim()}]);setMarketForm({name:"",type:"Day",mode:"Manual",status:"Active"});};
const deleteMarket=id=>{const item=markets.find(m=>m.id===id);setMarkets(markets.filter(m=>m.id!==id));if(item)setTimings(timings.filter(t=>t.market!==item.name));};
const addTiming=()=>{if(!timingForm.market)return alert("Select market");if(!timingForm.open||!timingForm.close||!timingForm.result)return alert("Timing required");setTimings([...timings,{id:Date.now(),...timingForm}]);setTimingForm({market:"",open:"",close:"",result:"",betClose:"5",days:"Mon - Sat"});};
const deleteTiming=id=>setTimings(timings.filter(t=>t.id!==id));
const addStarLine=()=>{if(!starForm.name.trim())return alert("Star line name required");if(!starForm.open||!starForm.close||!starForm.result)return alert("Star line timing required");setStarLines([...starLines,{id:Date.now(),...starForm,name:starForm.name.trim()}]);setStarForm({name:"",type:"Day",open:"",close:"",result:"",status:"Active"});};
const deleteStarLine=id=>setStarLines(starLines.filter(s=>s.id!==id));
return <div className="ca-page">
<aside className="ca-sidebar">
<div className="ca-logo">👑 <div><b>CASINO <span>ADMIN</span></b><small>ADMIN PANEL</small></div></div>
<nav><a className="active">🎰 Casino & Matka</a><a>⚙️ Casino Settings</a><a>🏦 Matka Markets</a><a>🕒 Matka Timings</a><a>⭐ Star Line</a><a>👥 Users Management</a><a>💳 Transactions</a><a>📊 Reports</a><a>👨‍💼 Admin Management</a><a>📄 Logs</a></nav>
<div className="ca-help"><b>Need Support?</b><p>Get help from our support team</p><button>WhatsApp Support</button><button className="tg">Telegram Support</button></div>
</aside>
<main className="ca-main">
<header className="ca-header"><div><h2>Casino & Matka Management</h2><p>Manage casino settings, matka markets, timings and star line</p></div><button>🌐 Visit Website</button></header>
<section className="ca-stats"><div><i>🎰</i><h3>{markets.length}</h3><p>Total Markets<br/><span>Active</span></p></div><div><i>🕒</i><h3>{timings.length}</h3><p>Total Timings<br/><span>Configured</span></p></div><div><i>⭐</i><h3>{starLines.length}</h3><p>Star Lines<br/><span>Configured</span></p></div><div><i>👥</i><h3>1,245</h3><p>Total Users<br/><span>Registered</span></p></div><div><i>✅</i><h3>Online</h3><p>System Status<br/><span>All Systems OK</span></p></div></section>
<section className="ca-grid">
<div className="ca-left">
<div className="ca-card"><h3><b>1</b> Casino Settings</h3><label>Casino Name</label><input name="name" value={casino.name} onChange={change}/><label>UPI ID</label><input name="upi" value={casino.upi} onChange={change}/><small>Enter your UPI ID for deposits</small><button className="save">💾 Save Casino Settings</button></div>
<div className="ca-card"><h3>Support Configuration</h3><label>WhatsApp Number</label><input name="whatsapp" value={casino.whatsapp} onChange={change}/><label>Telegram Username / Link</label><input name="telegram" value={casino.telegram} onChange={change}/><label>Email Support</label><input name="email" value={casino.email} onChange={change}/><button className="save">💾 Save Support Settings</button></div>
</div>
<div className="ca-card ca-table"><div className="ca-title"><h3><b>2</b> Matka Markets</h3></div><table><thead><tr><th>#</th><th>Market Name</th><th>Market Type</th><th>Result Mode</th><th>Status</th><th>Action</th></tr></thead><tbody>{markets.map((m,i)=><tr key={m.id}><td>{i+1}</td><td>{m.name}</td><td>{m.type}</td><td>{m.mode}</td><td className={m.status==="Active"?"green":"red"}>{m.status}</td><td><button className="del" onClick={()=>deleteMarket(m.id)}>🗑</button></td></tr>)}</tbody></table><div className="ca-form"><h3>Add Market</h3><input name="name" value={marketForm.name} onChange={changeMarket} placeholder="Market name"/><select name="type" value={marketForm.type} onChange={changeMarket}><option>Day</option><option>Night</option></select><select name="mode" value={marketForm.mode} onChange={changeMarket}><option>Manual</option><option>Auto</option></select><select name="status" value={marketForm.status} onChange={changeMarket}><option>Active</option><option>Inactive</option></select><button className="save" onClick={addMarket}>💾 Save Market</button></div></div>
<div className="ca-card ca-table"><div className="ca-title"><h3><b>3</b> Matka Timings</h3></div><table><thead><tr><th>#</th><th>Market Name</th><th>Open Time</th><th>Close Time</th><th>Result Time</th><th>Bet Close</th><th>Days</th><th>Action</th></tr></thead><tbody>{timings.map((t,i)=><tr key={t.id}><td>{i+1}</td><td>{t.market}</td><td>{t.open}</td><td>{t.close}</td><td>{t.result}</td><td>{t.betClose}</td><td>{t.days}</td><td><button className="del" onClick={()=>deleteTiming(t.id)}>🗑</button></td></tr>)}</tbody></table><div className="ca-form timing"><h3>Add Timing</h3><select name="market" value={timingForm.market} onChange={changeTiming}><option value="">Select Market</option>{markets.map(m=><option key={m.id} value={m.name}>{m.name}</option>)}</select><input name="open" value={timingForm.open} onChange={changeTiming} type="time"/><input name="close" value={timingForm.close} onChange={changeTiming} type="time"/><input name="result" value={timingForm.result} onChange={changeTiming} type="time"/><input name="betClose" value={timingForm.betClose} onChange={changeTiming} placeholder="Bet close before minutes"/><select name="days" value={timingForm.days} onChange={changeTiming}><option>Mon - Sat</option><option>Mon - Sun</option><option>Only Sunday</option></select><button className="save" onClick={addTiming}>💾 Save Timing</button></div></div>
<div className="ca-card ca-table ca-star-full"><div className="ca-title"><h3><b>4</b> Star Line</h3></div><table><thead><tr><th>#</th><th>Star Line Name</th><th>Type</th><th>Open</th><th>Close</th><th>Result</th><th>Status</th><th>Action</th></tr></thead><tbody>{starLines.map((s,i)=><tr key={s.id}><td>{i+1}</td><td>{s.name}</td><td>{s.type}</td><td>{s.open}</td><td>{s.close}</td><td>{s.result}</td><td className={s.status==="Active"?"green":"red"}>{s.status}</td><td><button className="del" onClick={()=>deleteStarLine(s.id)}>🗑</button></td></tr>)}</tbody></table><div className="ca-form star-form"><h3>Add Star Line</h3><input name="name" value={starForm.name} onChange={changeStar} placeholder="Star line name"/><select name="type" value={starForm.type} onChange={changeStar}><option>Day</option><option>Night</option></select><input name="open" value={starForm.open} onChange={changeStar} type="time"/><input name="close" value={starForm.close} onChange={changeStar} type="time"/><input name="result" value={starForm.result} onChange={changeStar} type="time"/><select name="status" value={starForm.status} onChange={changeStar}><option>Active</option><option>Inactive</option></select><button className="save" onClick={addStarLine}>⭐ Save Star Line</button></div></div>
</section>
</main>
</div>;
}